### ISSUE TITLE
CUDA error: out of memory 

### ISSUE THREAD

**Issue by ZHUJJFDU** [JDSobek/MedYOLO#22]
my gpu is rtx3080 10gb batch size=16

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|                                                                                                                                                                                                  | 0/2 [03:56<?, ?it/s] 
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MedYOLO-main\train.py", line 521, in <module>
    main(opt)
  File "C:\Users\Administrator\Desktop\MedYOLO-main\train.py", line 428, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\Administrator\Desktop\MedYOLO-main\train.py", line 227, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\Administrator\Desktop\MedYOLO-main\utils\datasets.py", line 43, in __iter__
    yield next(self.iterator)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\dataloader.py", line 1344, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\dataloader.py", line 1370, in _process_data
    data.reraise()
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\_utils.py", line 706, in reraise
    raise exception
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 38, in do_one_step
    data = pin_memory(data, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 80, in pin_memory
    return [pin_memory(sample, device) for sample in data]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 80, in <listcomp>
    return [pin_memory(sample, device) for sample in data]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\medyolo\Lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 59, in pin_memory
    return data.pin_memory(device)
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by JDSobek** [comment]
You need a smaller batch size. On default settings the small model will use ~35 GB of VRAM with batch size 8.  With only 10 GB you probably won't be able to run higher than batch size 2.

**Comment by rco98** [comment]
Hello! How can I use the configurations that use less memory? Is it enough to insert --cfg models3D/yolo3Dm.yaml or --cfg models3D/yolo3Dl.yaml in the command line of train? Are these the configurations that use 25 and 26 GB of memory, as reported in the article?
![Screenshot 2024-09-03 115318](https://github.com/user-attachments/assets/3c5b1683-bb5c-443d-bc82-1da89a2969f2)
Thank you in advance for your help!

**Comment by JDSobek** [comment]
> Is it enough to insert --cfg models3D/yolo3Dm.yaml or --cfg models3D/yolo3Dl.yaml in the command line of train?

You need to add the whole path ([or you can change this line to change the default model you run](https://github.com/JDSobek/MedYOLO/blob/main/train.py#L364)), but that will change the model that the script trains. However, the default model is the small model (MedYOLO-S), and the models you've quoted here are the medium (m) and large (l) models respectively.

What you'll need to do is probably add `--batch-size 2`, which will reduce your batch size to 2 images, and further adjust batch size depending on how much spare VRAM your GPU has when you run `train.py` like this.  It looks like the framework does batch accumulation (I apparently implemented [this](https://github.com/JDSobek/MedYOLO/blob/main/train.py#L261) and forgot about it) so it should still give you reasonable results.

If you really, really need to free up more VRAM I just added a nano version of the model, following the sizing of YOLOv5n. Add `--cfg ???/models3D/yolo3Dn.yaml` (with the full path to the model directory instead of ???) to the command line when you run `train.py`.  I'm pretty sure it should run fine, but I haven't tested it and have no idea how well it will perform.

**Comment by rco98** [comment]
Thank you very much! Your explanation was very clear and rapid regarding my request. I also appreciate the information about the nano version of the model. I’ll give it a try and see how it performs.
